# Default values for <CHARTNAME>.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Partially override the fullname template (will maintain the release name).
nameOverride: ""

## Fully override the fullname template.
fullnameOverride: ""

## Application configuration.
config: {}

## Image configuration options.
image:
  registry: ""
  repository: vaporio/<CHARTNAME>
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

## Pull secrets for pulling private images.
imagePullSecrets: []

## Values to encapsulate as Secrets.
## Note that Secret names must be a valid DNS subdomain name.
## ref: https://kubernetes.io/docs/concepts/configuration/secret/
secrets: []
#  - name: my-secret
#    value: foobar
#    type: Opaque
#    labels: {}
#    annotations: {}
#    mount: volume

## Enable/disable application metrics export.
metrics:
  enabled: false

## Service account configuration options.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  create: true
  annotations: {}
  labels: {}
  ## The name of the service account to use.
  ## If not set and create is true, a name is generated using the fullname template
  name: ""

## Deployment configuration options.
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
deployment:
  annotations: {}
  labels: {}
  replicas: 1

## Configuration options for container security context.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## Pod-specific configuration options.
## ref: https://kubernetes.io/docs/concepts/workloads/pods/
pod:
  annotations: {}
  labels: {}
  securityContext: {}
    # fsGroup: 2000

## Service configuration options.
## ref: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  annotations: {}
  labels: {}
  type: ClusterIP
  port: 80

## Ingress configuration options.
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  labels: {}
  hosts: []
  #  - host: chart-example.local
  #    paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

## Prometheus monitoring configuration.
## ref: https://docs.openshift.com/container-platform/4.4/rest_api/monitoring_apis/servicemonitor-monitoring-coreos-com-v1.html
serviceMonitor:
  enabled: false
  name: <CHARTNAME>-monitor
  port: http
  path: "/metrics"
  timeout: 4s
  interval: 5s

  namespace: ""
  labels: {}
    # vapor.io/monitor: application

  selectorNamespace: ""
  selectorLabels: {}

## Configure a horizontal pod autoscaler.
## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

## Configuration options for a PodDisruptionBudget.
## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget
podDisruptionBudget:
  enabled: false
#  annotations: {}
#  labels: {}
#  minAvailable: 2
#  maxUnavailable: 1

## Configuration options for pod security policies.
## ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
podSecurityPolicy:
  enabled: false
  name: ""
  annotations: {}
  labels: {}
  allowances: {}
    # privileged: true
    # runAsUser: 1000

## Readiness and liveness probe configuration options.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 3
  periodSeconds: 5
  failureThreshold: 2

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 3
  periodSeconds: 5
  failureThreshold: 2

## Specify arguments to pass to the container. By default, no arguments are passed.
## ref: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/
args: []

## Allow pass-through environment variable configuration.
## ref: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
env: []
  # - name: FOO
  #   value: bar

## Configure resource requests and limits.
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## Node labels for pod assignment.
## ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

## Tolerations for pod assignment.
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## Affinity for pod assignment.
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
