{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<CHARTNAME>.fullname" . }}-config
  labels:
    {{- include "<CHARTNAME>.labels" . | trim | nindent 4 }}
data:
  config.yml: {{ toYaml .Values.config | quote }}
{{- end }}
