{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<CHARTNAME>.fullname" . }}-config
  labels:
    {{- include "<CHARTNAME>.labels" . | trim | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
data:
  config.yml: {{ toYaml .Values.config | quote }}
{{- end }}
