{{- $globalLabels := .Values.globalLabels }}
{{- $labels := include "<CHARTNAME>.labels" . }}
{{- range $t, $secrets := .Values.secrets }}
{{- range $secret := $secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name | replace "_" "-" | lower }}
  {{- with $secret.annotations }}
  annotations:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  labels:
    {{- $labels | trim | nindent 4 }}
    {{- with $secret.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with $globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
type: {{ $secret.type | default "Opaque" }}
data:
  secret: {{ $secret.value | b64enc }}
{{- end }}
{{- end }}

